apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::471112954769:role/github-actions-test
      username: github-actions
      groups:
        - system:masters
